### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by hackergrrl** [ungoldman/open-source-maintenance-guidelines#1]
You link to so many great existing work! I don't really have much feedback to share: this is already a tremendously useful article.

On changelogs, I'm also fond of [changelog-init](https://github.com/hypermodules/changelog-init). On READMEs, [standard-readme](https://github.com/RichardLitt/standard-readme).

The tiniest of nitpicks: "Further Reading" under "Contributing Guidelines" is formatted differently than the others.

I really enjoyed (re-)reading this, Nate. Thank you! :tada:

**Comment by strugee** [comment]
@noffle changelog-init looks SO USEFUL. _Thank you._

**Comment by ungoldman** [comment]
Thanks so much for the feedback @noffle! I appreciate you taking the time to reread this. I was inspired by your work on [art-of-readme](https://github.com/noffle/art-of-readme) and wanted to give this article a second pass.

Credit goes to @bcomnes for creating `changelog-init` 🤝
